curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/overview/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/quick-setup-redis-cloud/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/concepts/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/concepts/data-persistence-redis-cloud/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/concepts/clustering-redis-cloud/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/concepts/data-eviction-policies/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/securing-redis-cloud-connections/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/setup-editing/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/setup-editing/create-subscription/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/setup-editing/viewing-subscription/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/setup-editing/changing-subscription-plan/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/setup-editing/creating-databases/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/setup-editing/viewing-editing-database/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/setup-editing/delete-databases/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/configuration/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/configuration/backups/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/configuration/security/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/configuration/monitoring-alerting-metrics/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/billing-history/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/payment-methods/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/system-logs/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/account-team-settings/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/administration/usage-reports/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/how-to/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/how-to/flush-db/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/how-to/aws-zone-mapping/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/how-to/flush_all-memcached-cloud/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/how-to/multiple-accounts/
curl -s -o /dev/null -w "%{http_code}" 	https://redislabs.com/redis-cloud-documentation/how-to/importing-dataset-redis-cloud/